### ISSUE TITLE
安装报错啊，请问怎么回事啊？

### ISSUE THREAD

**Issue by philboycn** [Zzm317/homebridge-mi-water-purifier#1]
npm install -g homebridge-mi-water-purifier                   
npm info it worked if it ends with ok                                           
npm info using npm@4.2.0                                                        
npm info using node@v7.10.0                                                     
npm info attempt registry request try #1 at 4:44:12 AM                          
npm http request GET https://registry.npmjs.org/homebridge-mi-water-purifier    
npm http 404 https://registry.npmjs.org/homebridge-mi-water-purifier            
npm ERR! Linux 3.10.102                                                         
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebri
dge-mi-water-purifier"                                                          
npm ERR! node v7.10.0                                                           
npm ERR! npm  v4.2.0                                                            
                                                                                
npm ERR! Cannot read property 'path' of null                                    
npm ERR!                                                                        
npm ERR! If you need help, you may report this error at:                        
npm ERR!     <https://github.com/npm/npm/issues>                                
                                                                                
npm ERR! Please include the following file with any support request:            
npm ERR!     /root/.npm/_logs/2017-10-29T04_44_14_565Z-debug.log

**Comment by Zzm317** [comment]
我没有推到npm
请下载然后上传到目录
